openapi: 3.0.1
info:
  title: PRIN135-Demo-10-OpenAPI
  description: Contains REST endpoints of PRIN135-Demo-10
  contact:
    name: Ralph Lee
    email: rlee@ceu.edu.ph
  version: "1.0"
servers:
- url: https://demo-09-db-integration.vercel.app
- url: https://demo-09-db-integration-git-open-api-leera01s-projects.vercel.app
paths:
  /tasks:
    get:
      tags:
      - Tasks
      summary: Returns all tasks.
      description: Returns all tasks.
      operationId: ""
      responses:
        "200":
          description: Tasks Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskGetResponse'
                x-content-type: application/json
        "404":
          description: Task not found
      x-swagger-router-controller: Tasks
    post:
      tags:
      - Tasks
      summary: Creates a task.
      description: Creates a task.
      operationId: ""
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
      responses:
        "201":
          description: Task created
      x-swagger-router-controller: Tasks
  /tasks/{id}:
    get:
      tags:
      - Tasks
      summary: Returns a task by specified id.
      description: Returns a task by specified id.
      operationId: ""
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskGetResponse'
        "404":
          description: Task not found
      x-swagger-router-controller: Tasks
    put:
      tags:
      - Tasks
      summary: Updates a task by specified id.
      description: Updates a task by specified id.
      operationId: ""
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
      responses:
        "200":
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskGetResponse'
        "404":
          description: Task not found
      x-swagger-router-controller: Tasks
    delete:
      tags:
      - Tasks
      summary: Deletes a task by specified id.
      description: Deletes a task by specified id.
      operationId: ""
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Task deleted
        "404":
          description: Task not found
      x-swagger-router-controller: Tasks
components:
  schemas:
    TaskCreateRequest:
      type: object
      properties:
        name:
          type: string
    TaskUpdateRequest:
      type: object
      properties:
        name:
          type: string
        isDone:
          type: boolean
    TaskGetResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        isDone:
          type: boolean
      example:
        name: name
        id: 0
        isDone: true
